export const immobilierElements = [
  {
    id: 1,
    title: 'Studio meublé 18m² - Quartier étudiant',
    price: 490,
    category: "Immobiliers",
    images: ["studio1.jpg"],
    date: new Date(),
    likes: 3,
    description: "Studio meublé idéal étudiant, proche des transports et commerces.",
    ref: 1010000001,
    informations: {
      transaction: "location",
      type: "Studio",
      surface: "18 m²",
      pieces: "1 pièce",
      chambres: "0",
      etage: "1er étage",
      chauffage: "Électrique",
      annee_construction: "2015",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: false,
      box: false,
      dpe: "D",
      ges: "C"
    }
  },
  {
    id: 2,
    title: 'Terrain constructible 500m² - Zone pavillonnaire',
    price: 75000,
    category: "Immobiliers",
    images: ["terrain.jpg"],
    date: new Date(),
    likes: 1,
    description: "Terrain viabilisé, idéal pour construction d'une maison familiale.",
    ref: 1010000002,
    informations: {
      transaction: "achat",
      type: "Terrain",
      surface: "500 m²",
      pieces: "-",
      chambres: "-",
      etage: "-",
      chauffage: "-",
      annee_construction: "-",
      terrain: true,
      piscine: false,
      jardin: false,
      parking: false,
      box: false,
      dpe: "Non concerné",
      ges: "Non concerné"
    }
  },
  {
    id: 3,
    title: 'Local commercial 90m² - Centre-ville',
    price: 1350,
    category: "Immobiliers",
    images: ["local.jpg"],
    date: new Date(),
    likes: 2,
    description: "Local avec vitrine sur rue passante, parfait pour commerce ou bureau.",
    ref: 1010000003,
    informations: {
      transaction: "location",
      type: "Local commercial",
      surface: "90 m²",
      pieces: "3 pièces",
      chambres: "-",
      etage: "RDC",
      chauffage: "Climatisation",
      annee_construction: "2002",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: true,
      box: false,
      dpe: "C",
      ges: "B"
    }
  },
  {
    id: 4,
    title: 'Garage fermé 15m² - Quartier résidentiel',
    price: 16000,
    category: "Immobiliers",
    images: ["garage.jpg"],
    date: new Date(),
    likes: 0,
    description: "Garage sécurisé accessible par portail automatique.",
    ref: 1010000004,
    informations: {
      transaction: "achat",
      type: "Garage",
      surface: "15 m²",
      pieces: "-",
      chambres: "-",
      etage: "Sous-sol",
      chauffage: "-",
      annee_construction: "1995",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: true,
      box: true,
      dpe: "Non concerné",
      ges: "Non concerné"
    }
  },
  {
    id: 5,
    title: 'Appartement T3 avec balcon - 70m²',
    price: 890,
    category: "Immobiliers",
    images: ["appart.jpg"],
    date: new Date(),
    likes: 5,
    description: "Appartement lumineux avec balcon et vue dégagée.",
    ref: 1010000005,
    informations: {
      transaction: "location",
      type: "Appartement",
      surface: "70 m²",
      pieces: "3 pièces",
      chambres: "2",
      etage: "3e étage",
      chauffage: "Gaz",
      annee_construction: "2010",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: true,
      box: false,
      dpe: "B",
      ges: "C"
    }
  },
  {
    id: 6,
    title: 'Maison de ville avec jardin et box',
    price: 215000,
    category: "Immobiliers",
    images: ["maison.jpg"],
    date: new Date(),
    likes: 4,
    description: "Maison rénovée avec extérieur, proche écoles et commerces.",
    ref: 1010000006,
    informations: {
      transaction: "achat",
      type: "Maison",
      surface: "105 m²",
      pieces: "5 pièces",
      chambres: "3",
      etage: "2 niveaux",
      chauffage: "Pompe à chaleur",
      annee_construction: "1985",
      terrain: true,
      piscine: false,
      jardin: true,
      parking: true,
      box: true,
      dpe: "C",
      ges: "C"
    }
  },
  {
    id: 7,
    title: 'Loft atypique - 110m² - Style industriel',
    price: 1500,
    category: "Immobiliers",
    images: ["loft.jpg"],
    date: new Date(),
    likes: 6,
    description: "Loft rénové avec grande hauteur sous plafond, proche du centre.",
    ref: 1010000007,
    informations: {
      transaction: "location",
      type: "Loft",
      surface: "110 m²",
      pieces: "3 pièces",
      chambres: "2",
      etage: "1er étage",
      chauffage: "Électrique",
      annee_construction: "Réhabilité en 2017",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: true,
      box: false,
      dpe: "D",
      ges: "B"
    }
  },
  {
    id: 8,
    title: 'Chalet bois avec terrasse - Montagne',
    price: 189000,
    category: "Immobiliers",
    images: ["chalet.jpg"],
    date: new Date(),
    likes: 7,
    description: "Chalet chaleureux avec vue sur les montagnes, terrain de 800m².",
    ref: 1010000008,
    informations: {
      transaction: "achat",
      type: "Chalet",
      surface: "80 m²",
      pieces: "4 pièces",
      chambres: "2",
      etage: "Plain-pied",
      chauffage: "Bois",
      annee_construction: "2008",
      terrain: true,
      piscine: false,
      jardin: true,
      parking: true,
      box: false,
      dpe: "E",
      ges: "D"
    }
  },
  {
    id: 9,
    title: 'Immeuble de rapport - 3 appartements',
    price: 395000,
    category: "Immobiliers",
    images: ["immeuble.jpg"],
    date: new Date(),
    likes: 2,
    description: "Investissement locatif avec 3 lots, bonne rentabilité.",
    ref: 1010000009,
    informations: {
      transaction: "achat",
      type: "Immeuble",
      surface: "210 m²",
      pieces: "9 pièces",
      chambres: "6",
      etage: "3 niveaux",
      chauffage: "Individuel électrique",
      annee_construction: "1975",
      terrain: false,
      piscine: false,
      jardin: false,
      parking: true,
      box: false,
      dpe: "C",
      ges: "C"
    }
  }
];
