export const itemsElements = [
    {
      id: 1,
      title: 'Nissan Note Entreprise 1.5 DCI 90',
      price: 2800,
      category: "Automobile",
      images: ["1.jpg", "2.jpg", "3.jpg"],
      date: new Date(),
      likes: 0,
      description: `Bonjour, moi c’est Kellian. Je serai ravi de réaliser votre déménagement ou le transport de vos meubles, œuvres d'art, etc.`,
      ref: 9926569973,
      informations: {
        version: "NOTE ENTREPRISE 1.5 DCI 90 CH EURO V FAP LIFE +",
        annee: "juin 2012",
        kilometrage: "224000 km",
        energie: "Diesel",
        couleur: "Jaune",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.2 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 2,
      title: 'Peugeot Partner 1.6 HDi',
      price: 3500,
      category: "Utilitaire",
      images: ["4.jpg", "5.jpg", "6.jpg"],
      date: new Date(),
      likes: 2,
      description: `Parfait pour le transport léger, faible consommation, bien entretenu.`,
      ref: 8823456789,
      informations: {
        version: "1.6 HDi 90 PREMIUM",
        annee: "mars 2014",
        kilometrage: "180000 km",
        energie: "Diesel",
        couleur: "Blanc",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "5.1 L / 100 km",
        puissance: "5 CV",
        nombre_de_places: "3 places"
      }
    },
    {
      id: 3,
      title: 'Renault Kangoo Express 1.5 dCi',
      price: 2900,
      category: "Utilitaire",
      images: ["7.jpg", "8.jpg"],
      date: new Date(),
      likes: 5,
      description: `Fiable et économique. Idéal pour activité professionnelle.`,
      ref: 7734567890,
      informations: {
        version: "1.5 dCi 75 Authentique",
        annee: "janvier 2011",
        kilometrage: "210000 km",
        energie: "Diesel",
        couleur: "Gris clair",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.8 L / 100 km",
        puissance: "5 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 4,
      title: 'Citroën Berlingo 1.6 BlueHDi',
      price: 4200,
      category: "Utilitaire",
      images: ["9.jpg"],
      date: new Date(),
      likes: 1,
      description: `Véhicule entretenu, parfait pour artisan ou livraison.`,
      ref: 6634567890,
      informations: {
        version: "1.6 BlueHDi 100 S&S",
        annee: "septembre 2016",
        kilometrage: "150000 km",
        energie: "Diesel",
        couleur: "Rouge",
        transmission: "Manuelle",
        portes: "5 portes",
        consommation: "4.5 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "3 places"
      }
    },
    {
      id: 5,
      title: 'Ford Transit Connect 1.5 TDCi',
      price: 5000,
      category: "Utilitaire",
      images: ["10.jpg", "11.jpg"],
      date: new Date(),
      likes: 4,
      description: `Camionnette récente, moteur fiable et faible kilométrage.`,
      ref: 5534567890,
      informations: {
        version: "1.5 TDCi 100 Trend",
        annee: "novembre 2018",
        kilometrage: "96000 km",
        energie: "Diesel",
        couleur: "Bleu foncé",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.0 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 6,
      title: 'Fiat Doblo Cargo Maxi 1.6 MJT',
      price: 3100,
      category: "Utilitaire",
      images: ["12.jpg", "13.jpg"],
      date: new Date(),
      likes: 3,
      description: `Véhicule en très bon état, utilisé pour transport de colis.`,
      ref: 4434567890,
      informations: {
        version: "1.6 MultiJet 105",
        annee: "mai 2013",
        kilometrage: "195000 km",
        energie: "Diesel",
        couleur: "Gris foncé",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.6 L / 100 km",
        puissance: "5 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 7,
      title: 'Opel Combo Cargo 1.5 D',
      price: 4700,
      category: "Utilitaire",
      images: ["14.jpg"],
      date: new Date(),
      likes: 6,
      description: `Bonne capacité de chargement, idéal pour artisans.`,
      ref: 3334567890,
      informations: {
        version: "1.5 Diesel 100 ch Edition",
        annee: "juillet 2019",
        kilometrage: "88000 km",
        energie: "Diesel",
        couleur: "Noir",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.3 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 8,
      title: 'Volkswagen Caddy 2.0 TDI',
      price: 5900,
      category: "Utilitaire",
      images: ["15.jpg", "16.jpg"],
      date: new Date(),
      likes: 7,
      description: `Volkswagen fiable, entretien rigoureux, prêt à l'emploi.`,
      ref: 2234567890,
      informations: {
        version: "2.0 TDI 102 Business",
        annee: "avril 2017",
        kilometrage: "123000 km",
        energie: "Diesel",
        couleur: "Blanc cassé",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "4.7 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "2 places"
      }
    },
    {
      id: 9,
      title: 'Renault Master L2H2 2.3 dCi',
      price: 8500,
      category: "Utilitaire",
      images: ["17.jpg"],
      date: new Date(),
      likes: 9,
      description: `Grand fourgon avec hayon. Idéal déménagements.`,
      ref: 1234567890,
      informations: {
        version: "2.3 dCi 130 ENERGY",
        annee: "février 2020",
        kilometrage: "72000 km",
        energie: "Diesel",
        couleur: "Blanc",
        transmission: "Manuelle",
        portes: "5 portes",
        consommation: "8.5 L / 100 km",
        puissance: "8 CV",
        nombre_de_places: "3 places"
      }
    },
    {
      id: 10,
      title: 'Mercedes Vito 111 CDI Long',
      price: 9700,
      category: "Utilitaire",
      images: ["18.jpg", "19.jpg"],
      date: new Date(),
      likes: 10,
      description: `Fourgon Mercedes robuste et élégant, très bon état général.`,
      ref: 1122334455,
      informations: {
        version: "111 CDI Long Pro",
        annee: "décembre 2019",
        kilometrage: "99000 km",
        energie: "Diesel",
        couleur: "Gris métallisé",
        transmission: "Manuelle",
        portes: "4 portes",
        consommation: "6.2 L / 100 km",
        puissance: "6 CV",
        nombre_de_places: "3 places"
      }
    }
  ];
  